// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_array_array_ap_fixed_8u_relu_config6_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> relu_array_array_ap_fixed_8u_relu_config6_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> relu_array_array_ap_fixed_8u_relu_config6_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> relu_array_array_ap_fixed_8u_relu_config6_s::ap_ST_fsm_state5 = "100";
const bool relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_boolean_1 = true;
const sc_lv<32> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv32_1 = "1";
const bool relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_boolean_0 = false;
const sc_lv<1> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv1_0 = "0";
const sc_lv<1> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv1_1 = "1";
const sc_lv<8> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv8_0 = "00000000";
const sc_lv<8> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv8_90 = "10010000";
const sc_lv<8> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv8_1 = "1";
const sc_lv<16> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> relu_array_array_ap_fixed_8u_relu_config6_s::ap_const_lv32_2 = "10";

relu_array_array_ap_fixed_8u_relu_config6_s::relu_array_array_ap_fixed_8u_relu_config6_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op56 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op56 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op28 );
    sensitive << ( io_acc_block_signal_op56 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( io_acc_block_signal_op28 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( io_acc_block_signal_op56 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln60_fu_325_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_V_data_0_V_blk_n);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_0_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_1_V_blk_n);
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_1_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_2_V_blk_n);
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_2_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_3_V_blk_n);
    sensitive << ( data_V_data_3_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_3_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_4_V_blk_n);
    sensitive << ( data_V_data_4_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_4_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_5_V_blk_n);
    sensitive << ( data_V_data_5_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_5_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_6_V_blk_n);
    sensitive << ( data_V_data_6_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_6_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_V_data_7_V_blk_n);
    sensitive << ( data_V_data_7_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln60_reg_473 );

    SC_METHOD(thread_data_V_data_7_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln60_reg_473 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_fu_331_p2);
    sensitive << ( i_0_reg_314 );

    SC_METHOD(thread_icmp_ln1494_1_fu_382_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_1_reg_488 );

    SC_METHOD(thread_icmp_ln1494_2_fu_395_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_213_reg_494 );

    SC_METHOD(thread_icmp_ln1494_3_fu_408_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_3_reg_500 );

    SC_METHOD(thread_icmp_ln1494_4_fu_421_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_4_reg_506 );

    SC_METHOD(thread_icmp_ln1494_5_fu_434_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_5_reg_512 );

    SC_METHOD(thread_icmp_ln1494_6_fu_447_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_6_reg_518 );

    SC_METHOD(thread_icmp_ln1494_7_fu_460_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_7_reg_524 );

    SC_METHOD(thread_icmp_ln1494_fu_369_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_data_V_0_reg_482 );

    SC_METHOD(thread_icmp_ln60_fu_325_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( i_0_reg_314 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_io_acc_block_signal_op28);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( data_V_data_3_V_empty_n );
    sensitive << ( data_V_data_4_V_empty_n );
    sensitive << ( data_V_data_5_V_empty_n );
    sensitive << ( data_V_data_6_V_empty_n );
    sensitive << ( data_V_data_7_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op56);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( res_V_data_3_V_full_n );
    sensitive << ( res_V_data_4_V_full_n );
    sensitive << ( res_V_data_5_V_full_n );
    sensitive << ( res_V_data_6_V_full_n );
    sensitive << ( res_V_data_7_V_full_n );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_data_0_V_blk_n);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_0_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_0_reg_482 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_fu_369_p2 );

    SC_METHOD(thread_res_V_data_0_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_1_V_blk_n);
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_1_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_1_reg_488 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_1_fu_382_p2 );

    SC_METHOD(thread_res_V_data_1_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_2_V_blk_n);
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_2_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_213_reg_494 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_2_fu_395_p2 );

    SC_METHOD(thread_res_V_data_2_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_3_V_blk_n);
    sensitive << ( res_V_data_3_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_3_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_3_reg_500 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_3_fu_408_p2 );

    SC_METHOD(thread_res_V_data_3_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_4_V_blk_n);
    sensitive << ( res_V_data_4_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_4_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_4_reg_506 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_4_fu_421_p2 );

    SC_METHOD(thread_res_V_data_4_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_5_V_blk_n);
    sensitive << ( res_V_data_5_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_5_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_5_reg_512 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_5_fu_434_p2 );

    SC_METHOD(thread_res_V_data_5_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_6_V_blk_n);
    sensitive << ( res_V_data_6_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_6_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_6_reg_518 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_6_fu_447_p2 );

    SC_METHOD(thread_res_V_data_6_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_V_data_7_V_blk_n);
    sensitive << ( res_V_data_7_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );

    SC_METHOD(thread_res_V_data_7_V_din);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( tmp_data_V_7_reg_524 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( icmp_ln1494_7_fu_460_p2 );

    SC_METHOD(thread_res_V_data_7_V_write);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_reg_473_pp0_iter1_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln60_fu_325_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_array_array_ap_fixed_8u_relu_config6_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_data_0_V_dout, "(port)data_V_data_0_V_dout");
    sc_trace(mVcdFile, data_V_data_0_V_empty_n, "(port)data_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_V_data_0_V_read, "(port)data_V_data_0_V_read");
    sc_trace(mVcdFile, data_V_data_1_V_dout, "(port)data_V_data_1_V_dout");
    sc_trace(mVcdFile, data_V_data_1_V_empty_n, "(port)data_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_V_data_1_V_read, "(port)data_V_data_1_V_read");
    sc_trace(mVcdFile, data_V_data_2_V_dout, "(port)data_V_data_2_V_dout");
    sc_trace(mVcdFile, data_V_data_2_V_empty_n, "(port)data_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_V_data_2_V_read, "(port)data_V_data_2_V_read");
    sc_trace(mVcdFile, data_V_data_3_V_dout, "(port)data_V_data_3_V_dout");
    sc_trace(mVcdFile, data_V_data_3_V_empty_n, "(port)data_V_data_3_V_empty_n");
    sc_trace(mVcdFile, data_V_data_3_V_read, "(port)data_V_data_3_V_read");
    sc_trace(mVcdFile, data_V_data_4_V_dout, "(port)data_V_data_4_V_dout");
    sc_trace(mVcdFile, data_V_data_4_V_empty_n, "(port)data_V_data_4_V_empty_n");
    sc_trace(mVcdFile, data_V_data_4_V_read, "(port)data_V_data_4_V_read");
    sc_trace(mVcdFile, data_V_data_5_V_dout, "(port)data_V_data_5_V_dout");
    sc_trace(mVcdFile, data_V_data_5_V_empty_n, "(port)data_V_data_5_V_empty_n");
    sc_trace(mVcdFile, data_V_data_5_V_read, "(port)data_V_data_5_V_read");
    sc_trace(mVcdFile, data_V_data_6_V_dout, "(port)data_V_data_6_V_dout");
    sc_trace(mVcdFile, data_V_data_6_V_empty_n, "(port)data_V_data_6_V_empty_n");
    sc_trace(mVcdFile, data_V_data_6_V_read, "(port)data_V_data_6_V_read");
    sc_trace(mVcdFile, data_V_data_7_V_dout, "(port)data_V_data_7_V_dout");
    sc_trace(mVcdFile, data_V_data_7_V_empty_n, "(port)data_V_data_7_V_empty_n");
    sc_trace(mVcdFile, data_V_data_7_V_read, "(port)data_V_data_7_V_read");
    sc_trace(mVcdFile, res_V_data_0_V_din, "(port)res_V_data_0_V_din");
    sc_trace(mVcdFile, res_V_data_0_V_full_n, "(port)res_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_V_data_0_V_write, "(port)res_V_data_0_V_write");
    sc_trace(mVcdFile, res_V_data_1_V_din, "(port)res_V_data_1_V_din");
    sc_trace(mVcdFile, res_V_data_1_V_full_n, "(port)res_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_V_data_1_V_write, "(port)res_V_data_1_V_write");
    sc_trace(mVcdFile, res_V_data_2_V_din, "(port)res_V_data_2_V_din");
    sc_trace(mVcdFile, res_V_data_2_V_full_n, "(port)res_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_V_data_2_V_write, "(port)res_V_data_2_V_write");
    sc_trace(mVcdFile, res_V_data_3_V_din, "(port)res_V_data_3_V_din");
    sc_trace(mVcdFile, res_V_data_3_V_full_n, "(port)res_V_data_3_V_full_n");
    sc_trace(mVcdFile, res_V_data_3_V_write, "(port)res_V_data_3_V_write");
    sc_trace(mVcdFile, res_V_data_4_V_din, "(port)res_V_data_4_V_din");
    sc_trace(mVcdFile, res_V_data_4_V_full_n, "(port)res_V_data_4_V_full_n");
    sc_trace(mVcdFile, res_V_data_4_V_write, "(port)res_V_data_4_V_write");
    sc_trace(mVcdFile, res_V_data_5_V_din, "(port)res_V_data_5_V_din");
    sc_trace(mVcdFile, res_V_data_5_V_full_n, "(port)res_V_data_5_V_full_n");
    sc_trace(mVcdFile, res_V_data_5_V_write, "(port)res_V_data_5_V_write");
    sc_trace(mVcdFile, res_V_data_6_V_din, "(port)res_V_data_6_V_din");
    sc_trace(mVcdFile, res_V_data_6_V_full_n, "(port)res_V_data_6_V_full_n");
    sc_trace(mVcdFile, res_V_data_6_V_write, "(port)res_V_data_6_V_write");
    sc_trace(mVcdFile, res_V_data_7_V_din, "(port)res_V_data_7_V_din");
    sc_trace(mVcdFile, res_V_data_7_V_full_n, "(port)res_V_data_7_V_full_n");
    sc_trace(mVcdFile, res_V_data_7_V_write, "(port)res_V_data_7_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, data_V_data_0_V_blk_n, "data_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln60_reg_473, "icmp_ln60_reg_473");
    sc_trace(mVcdFile, data_V_data_1_V_blk_n, "data_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_V_data_2_V_blk_n, "data_V_data_2_V_blk_n");
    sc_trace(mVcdFile, data_V_data_3_V_blk_n, "data_V_data_3_V_blk_n");
    sc_trace(mVcdFile, data_V_data_4_V_blk_n, "data_V_data_4_V_blk_n");
    sc_trace(mVcdFile, data_V_data_5_V_blk_n, "data_V_data_5_V_blk_n");
    sc_trace(mVcdFile, data_V_data_6_V_blk_n, "data_V_data_6_V_blk_n");
    sc_trace(mVcdFile, data_V_data_7_V_blk_n, "data_V_data_7_V_blk_n");
    sc_trace(mVcdFile, res_V_data_0_V_blk_n, "res_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, icmp_ln60_reg_473_pp0_iter1_reg, "icmp_ln60_reg_473_pp0_iter1_reg");
    sc_trace(mVcdFile, res_V_data_1_V_blk_n, "res_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_V_data_2_V_blk_n, "res_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_V_data_3_V_blk_n, "res_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_V_data_4_V_blk_n, "res_V_data_4_V_blk_n");
    sc_trace(mVcdFile, res_V_data_5_V_blk_n, "res_V_data_5_V_blk_n");
    sc_trace(mVcdFile, res_V_data_6_V_blk_n, "res_V_data_6_V_blk_n");
    sc_trace(mVcdFile, res_V_data_7_V_blk_n, "res_V_data_7_V_blk_n");
    sc_trace(mVcdFile, i_0_reg_314, "i_0_reg_314");
    sc_trace(mVcdFile, icmp_ln60_fu_325_p2, "icmp_ln60_fu_325_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, io_acc_block_signal_op28, "io_acc_block_signal_op28");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, io_acc_block_signal_op56, "io_acc_block_signal_op56");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_331_p2, "i_fu_331_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_data_V_0_reg_482, "tmp_data_V_0_reg_482");
    sc_trace(mVcdFile, tmp_data_V_1_reg_488, "tmp_data_V_1_reg_488");
    sc_trace(mVcdFile, tmp_data_V_213_reg_494, "tmp_data_V_213_reg_494");
    sc_trace(mVcdFile, tmp_data_V_3_reg_500, "tmp_data_V_3_reg_500");
    sc_trace(mVcdFile, tmp_data_V_4_reg_506, "tmp_data_V_4_reg_506");
    sc_trace(mVcdFile, tmp_data_V_5_reg_512, "tmp_data_V_5_reg_512");
    sc_trace(mVcdFile, tmp_data_V_6_reg_518, "tmp_data_V_6_reg_518");
    sc_trace(mVcdFile, tmp_data_V_7_reg_524, "tmp_data_V_7_reg_524");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, icmp_ln1494_fu_369_p2, "icmp_ln1494_fu_369_p2");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_382_p2, "icmp_ln1494_1_fu_382_p2");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_395_p2, "icmp_ln1494_2_fu_395_p2");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_408_p2, "icmp_ln1494_3_fu_408_p2");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_421_p2, "icmp_ln1494_4_fu_421_p2");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_434_p2, "icmp_ln1494_5_fu_434_p2");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_447_p2, "icmp_ln1494_6_fu_447_p2");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_460_p2, "icmp_ln1494_7_fu_460_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

relu_array_array_ap_fixed_8u_relu_config6_s::~relu_array_array_ap_fixed_8u_relu_config6_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_fu_325_p2.read()))) {
        i_0_reg_314 = i_fu_331_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_314 = ap_const_lv8_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln60_reg_473 = icmp_ln60_fu_325_p2.read();
        icmp_ln60_reg_473_pp0_iter1_reg = icmp_ln60_reg_473.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_data_V_0_reg_482 = data_V_data_0_V_dout.read();
        tmp_data_V_1_reg_488 = data_V_data_1_V_dout.read();
        tmp_data_V_213_reg_494 = data_V_data_2_V_dout.read();
        tmp_data_V_3_reg_500 = data_V_data_3_V_dout.read();
        tmp_data_V_4_reg_506 = data_V_data_4_V_dout.read();
        tmp_data_V_5_reg_512 = data_V_data_5_V_dout.read();
        tmp_data_V_6_reg_518 = data_V_data_6_V_dout.read();
        tmp_data_V_7_reg_524 = data_V_data_7_V_dout.read();
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[2];
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op56.read())));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op56.read())));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op56.read())));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op28.read()));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op56.read()));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln60_fu_325_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n.read();
    } else {
        data_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_V_data_0_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n.read();
    } else {
        data_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_V_data_1_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n.read();
    } else {
        data_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_V_data_2_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n.read();
    } else {
        data_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_3_V_read = ap_const_logic_1;
    } else {
        data_V_data_3_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n.read();
    } else {
        data_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_4_V_read = ap_const_logic_1;
    } else {
        data_V_data_4_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_5_V_blk_n = data_V_data_5_V_empty_n.read();
    } else {
        data_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_5_V_read = ap_const_logic_1;
    } else {
        data_V_data_5_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_6_V_blk_n = data_V_data_6_V_empty_n.read();
    } else {
        data_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_6_V_read = ap_const_logic_1;
    } else {
        data_V_data_6_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0))) {
        data_V_data_7_V_blk_n = data_V_data_7_V_empty_n.read();
    } else {
        data_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_data_V_data_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln60_reg_473.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_7_V_read = ap_const_logic_1;
    } else {
        data_V_data_7_V_read = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_i_fu_331_p2() {
    i_fu_331_p2 = (!i_0_reg_314.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(i_0_reg_314.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_1_fu_382_p2() {
    icmp_ln1494_1_fu_382_p2 = (!tmp_data_V_1_reg_488.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_1_reg_488.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_2_fu_395_p2() {
    icmp_ln1494_2_fu_395_p2 = (!tmp_data_V_213_reg_494.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_213_reg_494.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_3_fu_408_p2() {
    icmp_ln1494_3_fu_408_p2 = (!tmp_data_V_3_reg_500.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_3_reg_500.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_4_fu_421_p2() {
    icmp_ln1494_4_fu_421_p2 = (!tmp_data_V_4_reg_506.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_4_reg_506.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_5_fu_434_p2() {
    icmp_ln1494_5_fu_434_p2 = (!tmp_data_V_5_reg_512.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_5_reg_512.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_6_fu_447_p2() {
    icmp_ln1494_6_fu_447_p2 = (!tmp_data_V_6_reg_518.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_6_reg_518.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_7_fu_460_p2() {
    icmp_ln1494_7_fu_460_p2 = (!tmp_data_V_7_reg_524.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_7_reg_524.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln1494_fu_369_p2() {
    icmp_ln1494_fu_369_p2 = (!tmp_data_V_0_reg_482.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(tmp_data_V_0_reg_482.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_icmp_ln60_fu_325_p2() {
    icmp_ln60_fu_325_p2 = (!i_0_reg_314.read().is_01() || !ap_const_lv8_90.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_314.read() == ap_const_lv8_90);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_io_acc_block_signal_op28() {
    io_acc_block_signal_op28 = (data_V_data_0_V_empty_n.read() & data_V_data_1_V_empty_n.read() & data_V_data_2_V_empty_n.read() & data_V_data_3_V_empty_n.read() & data_V_data_4_V_empty_n.read() & data_V_data_5_V_empty_n.read() & data_V_data_6_V_empty_n.read() & data_V_data_7_V_empty_n.read());
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_io_acc_block_signal_op56() {
    io_acc_block_signal_op56 = (res_V_data_0_V_full_n.read() & res_V_data_1_V_full_n.read() & res_V_data_2_V_full_n.read() & res_V_data_3_V_full_n.read() & res_V_data_4_V_full_n.read() & res_V_data_5_V_full_n.read() & res_V_data_6_V_full_n.read() & res_V_data_7_V_full_n.read());
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n.read();
    } else {
        res_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_0_V_din() {
    res_V_data_0_V_din = (!icmp_ln1494_fu_369_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_fu_369_p2.read()[0].to_bool())? tmp_data_V_0_reg_482.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_V_data_0_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n.read();
    } else {
        res_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_1_V_din() {
    res_V_data_1_V_din = (!icmp_ln1494_1_fu_382_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_1_fu_382_p2.read()[0].to_bool())? tmp_data_V_1_reg_488.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_V_data_1_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n.read();
    } else {
        res_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_2_V_din() {
    res_V_data_2_V_din = (!icmp_ln1494_2_fu_395_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_2_fu_395_p2.read()[0].to_bool())? tmp_data_V_213_reg_494.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_V_data_2_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n.read();
    } else {
        res_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_3_V_din() {
    res_V_data_3_V_din = (!icmp_ln1494_3_fu_408_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_3_fu_408_p2.read()[0].to_bool())? tmp_data_V_3_reg_500.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_3_V_write = ap_const_logic_1;
    } else {
        res_V_data_3_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n.read();
    } else {
        res_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_4_V_din() {
    res_V_data_4_V_din = (!icmp_ln1494_4_fu_421_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_4_fu_421_p2.read()[0].to_bool())? tmp_data_V_4_reg_506.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_4_V_write = ap_const_logic_1;
    } else {
        res_V_data_4_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n.read();
    } else {
        res_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_5_V_din() {
    res_V_data_5_V_din = (!icmp_ln1494_5_fu_434_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_5_fu_434_p2.read()[0].to_bool())? tmp_data_V_5_reg_512.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_5_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_5_V_write = ap_const_logic_1;
    } else {
        res_V_data_5_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n.read();
    } else {
        res_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_6_V_din() {
    res_V_data_6_V_din = (!icmp_ln1494_6_fu_447_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_6_fu_447_p2.read()[0].to_bool())? tmp_data_V_6_reg_518.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_6_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_6_V_write = ap_const_logic_1;
    } else {
        res_V_data_6_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()))) {
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n.read();
    } else {
        res_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_7_V_din() {
    res_V_data_7_V_din = (!icmp_ln1494_7_fu_460_p2.read()[0].is_01())? sc_lv<16>(): ((icmp_ln1494_7_fu_460_p2.read()[0].to_bool())? tmp_data_V_7_reg_524.read(): ap_const_lv16_0);
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_res_V_data_7_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln60_reg_473_pp0_iter1_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_7_V_write = ap_const_logic_1;
    } else {
        res_V_data_7_V_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_start_out() {
    start_out = real_start.read();
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void relu_array_array_ap_fixed_8u_relu_config6_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln60_fu_325_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln60_fu_325_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

