apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: UNIQUE_NAME
  namespace: YOUR_NAMESPACE
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi