apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: NAME
spec:
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: NAME
    spec:
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: pub-key # Name of secret generated
          propagationMethod:
            qemuGuestAgent:
              users:      # Add a field for each user you use ssh to connect to
              - admin
              - user1
              - user2
              - user3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                - us-west
      architecture: amd64
      networks:
      - name: default
        pod: {}
      domain:
        cpu:
          cores: 21
        devices:
          interfaces:
          - name: default
            masquerade: {}
            macAddress: "02:00:00:00:00:02"
          inputs:
          - bus: usb
            name: tablet1
            type: tablet
          autoattachGraphicsDevice: true
          autoattachSerialConsole: true
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: datavolumedisk1 
          - disk:   
              bus: virtio                  
            name: toolvol
          # - disk:
          #     bus: virtio                  # Add a field for each disk you want to mount
          #   name: backupvol
        machine:
          type: q35
        resources:
          limits:
            ephemeral-storage: 50Gi
            memory: 64Gi
            cpu: 21
          requests:
            ephemeral-storage: 50Gi
            memory: 64Gi
            cpu: 21
      volumes:
      - name: datavolumedisk1
        persistentVolumeClaim:
          claimName: main-disk             # Change this to the one created with vm_disk.yaml 
      - name: toolvol                      # Leave this uncommented if you want access to a disk with preloaded vivado 2019.1 and 2025.1 and you're in the acme-lab namespace
        persistentVolumeClaim:
          claimName: xilinxvol
      # - name: backupvol                 # Add a field for each disk you want to mount
      #   persistentVolumeClaim:
      #     claimName: your-backup
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
            users:
            - name: admin
              groups: sudo
              shell: /bin/bash
              sudo: ["ALL=(ALL) NOPASSWD:ALL"]
              lock_passwd: false
            network:
              version: 2
              ethernets:
                enp1s0:
                  dhcp4: true
        name: cloudinit